#!/usr/bin/env sh
# Regenerate src/version.h from the fap version + current git short hash, so the
# About screen can show exactly which build is flashed. Run before `ufbt` (locally
# and in CI). Safe to commit the result; it's refreshed on every build. Falls back
# to "nogit" when built outside a checkout (tarball, etc).
set -e
HERE=$(CDPATH= cd "$(dirname "$0")" && pwd)
VER=$(sed -n 's/.*fap_version="\([^"]*\)".*/\1/p' "$HERE/application.fam" | head -1)
[ -n "$VER" ] || VER="0.0"
HASH=$(git -C "$HERE" rev-parse --short=7 HEAD 2>/dev/null || echo nogit)
cat > "$HERE/src/version.h" <<EOF
#pragma once
// Generated by gen_version.sh — do not edit; refreshed on every build.
#define PWNPAL_APP_VERSION "v$VER"
#define PWNPAL_GIT_HASH "$HASH"
EOF
echo "version.h: v$VER $HASH"
